run_specs:
  tags: ['test']
  task_name: test


paths:
  run_dir: log/${run_specs.task_name}

callbacks:
  model_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    # dirpath: ${paths.run_dir}/checkpoints
    filename: epoch_{epoch:03d}-{val/loss:.3e}
    monitor: val/loss
    verbose: false
    save_last: true
    save_top_k: 5
    mode: min
    auto_insert_metric_name: false
    save_weights_only: false
    every_n_train_steps: null
    train_time_interval: null
    every_n_epochs: null
    save_on_train_epoch_end: null
  early_stopping:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val/loss
    min_delta: 0.0
    patience: 100
    verbose: false
    mode: min
    strict: true
    check_finite: true
    stopping_threshold: null
    divergence_threshold: null
    check_on_train_epoch_end: null
  model_summary:
    _target_: lightning.pytorch.callbacks.RichModelSummary
    max_depth: -1
  rich_progress_bar:
    _target_: src.utils.rich_utils.CustomRichProgressBar
    theme:
      _target_: lightning.pytorch.callbacks.progress.rich_progress.RichProgressBarTheme
      metrics_format: .2e
logger:
  tensorboard:
    _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
    save_dir: ${paths.run_dir}/tensorboard/
    name: null
    log_graph: false
    default_hp_metric: true
    prefix: ''
  
  # csv:
  #   _target_: lightning.pytorch.loggers.csv_logs.CSVLogger
  #   save_dir: ${paths.run_dir}
  #   name: csv/
  #   prefix: ''
  # wandb:
  #   _target_: lightning.pytorch.loggers.wandb.WandbLogger
  #   save_dir: ${paths.run_dir}
  #   offline: false
  #   id: null
  #   anonymous: null
  #   project: Koopman
  #   log_model: false
  #   prefix: ''
  #   # entity: Long_Memory_Arena
  #   group: test
  #   tags: ${run_specs.tags}
  #   job_type: ''
  #   name: ${run_specs.task_name}
  